import Head from "next/head";
import Header from "@/Components/Header";
import Section from "@/Components/Landing Page/Section1";
import Section2 from "@/Components/Landing Page/Section2";
import Footer from "@/Components/Footer";
import Signup from "./signup";
import HeroSection from "@/Components/userpage/HeroSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Section />
        <Section2 />
        <Footer />

        <HeroSection />
      </main>
    </>
  );
}
